### PR TITLE
New meta-function: pluck

### PR DESCRIPTION
**Pull request by jll63**
I started using bolts in my openmethods library. Super useful, but I ran short of one meta-function. So here it is.

### CODE REVIEW

**Comment by aliak00** [comment]
Nice! This is a great idea!

Since it's very specific to `AliasPack`, what do you think of putting it inside the template instead? Also the functionality is maybe more `pluck` and not `slice`? (as slicing usually means a range of consecutive values - especially in D)

I looked at your usecase as well, and with an method `pluck` your code would go form this:

```
    foreach (
      cls;
      openmethods.staticSlice!(
        openmethods.AliasPack!(SpecParams),
        openmethods.AliasPack!(TheMethod.virtualPositions)).Unpack) {
      si.vp ~= cls.classinfo;
    }
```

to this:

```
    foreach (
      cls;
      openmethods.AliasPack!(SpecParams)
        .pluck!(TheMethod.virtualPositions)) {
      si.vp ~= cls.classinfo;
    }
```

**Comment by jll63** [comment]
Regarding the name, I drew inspiration from Perl. But I find `pluck` quite cute.

Regarding the arguments and return values...I had the impression that you wanted to work in terms of `AliasPack`s rather than `AliasSeq`s. Indeed taking the positions, and returning the values, via `AliasSeq`s instead of `AliasPack`s makes the openmethods code fragment much simpler.

OTOH, I find `AliasPack`s more composable. Essentially, `AliasSeq` is a Perl list, while `AliasPack` is a Lisp list. If we keep things "more" packed, we can do some funky Lisp-like things, e.g.:

```
template staticPlus(Values...)
{
  static if (Values.length == 0) {
    enum staticPlus = 0;
  } else {
    enum staticPlus = Values[0] + staticPlus!(Values[1..$]);
  }
}

template staticApply(alias Fun, alias Pack)
{
  alias staticApply = Fun!(Pack.Unpack);
}

template staticMap(alias Fun, Packs...)
{
  static if (Packs.length == 0) {
    alias staticMap = AliasPack!();
  } else static if (Packs[0].length == 0) {
    alias staticMap = AliasPack!();
  } else {
    static import std.meta;
    alias PackHead(alias Pack) = Pack.Head;
    alias PackTail(alias Pack) = Pack.Tail;
    alias staticMap = AliasPack!(
      Fun!(std.meta.staticMap!(PackHead, Packs)),
      staticMap!(
        Fun,
        std.meta.staticMap!(PackTail, Packs)).Unpack);
  }
}

///
unittest
{
  static assert(staticPlus!(1, 4, 7) == 12);
  static assert(staticApply!(staticPlus, AliasPack!(1, 4, 7)) == 12);

  static assert(staticMap!(staticPlus).equals!());
  static assert(staticMap!(staticPlus, AliasPack!(), AliasPack!()).equals!());

  static assert(
    staticMap!(
      staticPlus,
      AliasPack!(1, 2, 3))
    .equals!(1, 2, 3));

  static assert(
    staticMap!(
      staticPlus,
      AliasPack!(1, 2, 3),
      AliasPack!(10, 11, 12))
    .equals!(11, 13, 15));

  static assert(
    staticMap!(
      staticSlice,
      AliasPack!(AliasPack!(int, char, float), AliasPack!(1, 4, 9)),
      AliasPack!(AliasPack!(0,  2), AliasPack!(1,  2)))
    .equals!(AliasPack!(int, float), AliasPack!(4, 9)));
}
```
I'm just musing here...I don't know if you want to take bolts down that route.

Regarding free vs member function: obviously I have a bias towards free ;-) My examples above (the `PackHead` and `PackTail` aliases) show that free is more composable. They also show that it is trivial to make a free equivalent of a template on the fly. Hey, maybe we should approach Walter and Andrei and suggest UTIS, in addition to UFCS?

One more thing. While working on these examples, I used `pragma(trace, Pack.stringof)` and the result was not very helpful. Would you be interested in another PR with an `AliasPack.stringof` method that recursively stringifies the packs?

As for this PR, if after reading this you still feel good about `AliasPack.pluck` taking and returning tuples, so do I, and I will implement your suggestions. Please let me know...

**Comment by aliak00** [comment]
> Regarding the name, I drew inspiration from Perl. But I find pluck quite cute.

Aha. It indeed makes sense in the perl sense. Since you think pluck is cute, let's go with that for now! Another reason is that I tried to use the range operator as a template argument and that doesn't work. So I think I'd like to save `staticSlice` for a d-style-slice.

> I'm just musing here...I don't know if you want to take bolts down that route.

That stuff looks great and I like it! I usually just wait for a use-case to pop up before adding anything so if any of that is needed in user code, and there isn't an already-simpler way to do it, then you'll find no objections here ;)

> Regarding free vs member function: obviously I have a bias towards free ;-) My examples above (the PackHead and PackTail aliases) show that free is more composable. They also show that it is trivial to make a free equivalent of a template on the fly. Hey, maybe we should approach Walter and Andrei and suggest UTIS, in addition to UFCS?

I also usually have a preference for free as well ;) Can you envision (or even better if you already have) a case where the free function `staticPluck` needs composition or benefits from being free over a member?

I'm thinking something like:

```
staticMap!(ApplyRight!(staticPluck, Positions), sequenceOfPacks);
```

Would a member `pluck` that would be...

```
enum mapFunc(alias pack) = pack.slice!Positions
staticMap!(mapFunc, sequenceOfPacks);
```

Ok, I think you're right here. Let's keep it free.

Which brings me to:

> Regarding the arguments and return values...I had the impression that you wanted to work in terms of AliasPacks rather than AliasSeqs. Indeed taking the positions, and returning the values, via AliasSeqs instead of AliasPacks makes the openmethods code fragment much simpler.

I think my preference is towards the call site when possible. But in this case, I'm now thinking maybe an array of ulong for positions? As that seems a lot more straight forward in this case?

```
template staticPluck(alias Pack, ulong[] Positions) { ... }
```

An alias seq of num can be turned to an array by surrounding it with brackets, and typed is (usually) better than untyped. So maybe that?

And the return also I think you're right in that it should stay a pack.

> One more thing. While working on these examples, I used pragma(trace, Pack.stringof) and the result was not very helpful. Would you be interested in another PR with an AliasPack.stringof method that recursively stringifies the packs?

Have you seen `bolts.traits.StringOf`?

**Comment by jll63** [comment]
> maybe an array of ulong for positions?

Yes. good. The reason why I started with the positions in an `AliasPack` is that I felt that having a trailing list of positions may make things more difficult in the future, because, you know, `...` gobbles up everything! What if at some point we want a multi-dimensional `pluck`?

> `template staticPluck(alias Pack, ulong[] Positions) { ... }`

Are we going for `staticPluck` or plain `pluck`? Do you have a naming scheme? E.g. why `Flatten`, not `flatten` (it's a function not a type) or `staticFlatten` (it's compile-time). Personally I find that adding a `static` prefix to everything may lead to a form of duckspeak.

Let me know what you prefer...

> Have you seen `bolts.traits.StringOf`?

Only after writing my previous post haha.

I pushed a couple of commits (instead of editing history; you can always squash-merge later):
* I renamed `staticSlice` to `pluck`. Do you prefer `staticPluck`?
* I added a constraint, so that `pluck`/`staticPluck` can be overloaded. The downside is that I `import std.traits: isInstanceOf`. Is that a problem? It's not a public import anyway. Another option is to use a static import. Or `from`.

**Comment by aliak00** [comment]
> Are we going for staticPluck or plain pluck? Do you have a naming scheme? E.g. why Flatten, not flatten (it's a function not a type) or staticFlatten (it's compile-time). Personally I find that adding a static prefix to everything may lead to a form of duckspeak.

I have not thought that much about the naming scheme in meta. I tried to follow phobos more or less. `Flatten` turned out that way because of `Filter` from `std`. My initial thought was a capital letter for functions that operated on type information. But `staticMap` throws a wrench in that. I agree about the `static` prefix with you though. So maybe just pascal-case everything in the meta module.

So `Zip`, `Pluck`, `Flatten`, etc. 

>I renamed staticSlice to pluck. Do you prefer staticPluck? I added a constraint, so that pluck/staticPluck can be overloaded. The downside is that I import std.traits: isInstanceOf. Is that a problem? It's not a public import anyway. Another option is to use a static import. Or from

Good on both accounts. Lazy importing is preferred. But that can go in anther commit. And the naming needs to be thought about more holistically in the meta module I feel now that you bring it up! I'll do that over the next couple days before the next release! Do you have any suggestions other than removing the static prefix?

**Comment by jll63** [comment]
> `staticMap` throws a wrench in that.

Yeah, it didn't even need the `static`, as `Map` would not have conflicted.

> So `Zip`, `Pluck`, `Flatten`, etc.

I prefer this to `staticThis` and `staticThat` ;-)

> Do you have any suggestions other than removing the static prefix?

Not at the moment, but now that `bolts` is on my radar, I may soon :)

**Pull request merged**
